config/routes.rb
Rails.application.routes.draw do
  get 'user_marketings/unsubscribe'
  # Forest Admin
  mount ForestLiana::Engine => '/forest'

  # Devise
  devise_for :users, controllers: { sessions: "sessions", registrations: 'registrations'}
  devise_scope :user do
    get "/onboarding/starter-pack" => "registrations#new_starter", as: "onboarding_starter_pack"
    get "/onboarding/settle-in-pack" => "registrations#new_settle_in", as: "onboarding_settle_in"
    post "/onboarding/:resource" => "registrations#create", as: 'registration'
  end

  # Update Password
  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end


  #Unsubscribe email
  get 'unsubscribe/confimation/:user_id', to: 'user_marketings#unsubscribe_confimation', as: 'unsubscribe_confirmation'
  put 'unsubscribe/:user_id', to: 'user_marketings#unsubscribe', as: 'unsubscribe'


  # Onboarding
  get 'onboarding/new-journey/:pack', to: 'houses#new', as: 'new_house'
  get 'onboarding/my-services/:pack', to: 'carts#new', as: 'new_cart'
  get 'onboarding/my-services/packs/:order_id', to: 'packs#index', as: 'packs'
  get 'onboarding/starter-pack/:order_id/shipping', to: 'shippings#new', as: 'new_shipping'
  get 'onboarding/starter-pack/:order_id/pickup', to: 'pickups#new', as: 'new_pickup'
  get 'onboarding/:order_id/checkout', to: 'payments#new', as: 'checkout'
  post 'payments/:order_id', to: 'payments#create', as: 'payments'
  get 'congratulations/:order_id', to: 'orders#congratulations', as: 'congratulations'
  get 'congratulations/starter/:order_id', to: 'orders#starter', as: 'starter_congratulations'
  get 'congratulations/settle-in/:order_id', to: 'orders#settle_in', as: 'settle_in_congratulations'
  get 'onboarding/legal/subscriptions/:order_id', to: 'subscriptions#new', as: 'new_subscription'


  put 'cancel-subscription/:order_id', to: 'subscriptions#cancel', as: 'cancel_subscription'

  # Dashboard
  get 'dashboard', to: 'dashboards#index', as: 'dashboard'
  get 'dashboard/payment-details', to: 'payment_details#index', as: 'payment_details'
  get 'dashboard/add-payment-details', to: 'payment_details#new', as: 'new_payment_details'
  get 'dashboard/profile', to: 'users#profile', as: 'update_profile'
  put 'dashboard/profile/update', to: 'users#update', as: 'dashboard_update_profile'
  post 'dashboard/add-payment-details', to: 'payment_details#create', as: 'payment_detail'

  get 'dashboard/active-services/:plan_id', to: 'dashboards#plan', as: 'dashboard_plan'
  get 'dashboard/orders', to: 'dashboards#orders', as: 'dashboard_orders'

  # HTTP errors
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'

  # Static pages
  root 'pages#home'
  get 'privacy', to: 'pages#privacy', as: 'privacy'
  get 'cookies', to: 'pages#cookies'
  get 'terms', to: 'pages#terms', as: 'terms'
  get 'how_it_works', to: 'pages#how_it_works'
  get 'about', to: 'pages#about'
  get 'pricing/starter-pack', to: 'pages#starter_pack', as: "pricing_starter_pack"
  get 'pricing/settle-in-pack', to: 'pages#settle_in', as: "pricing_settle_in"
  get 'thankyou', to: 'pages#thank_you', as: 'thank_you'
  get 'home', to:"pages#home"

  # Generate invoice
  get 'dashboard/invoice/:order_id', to: 'orders#invoice', as: 'invoice'

  # Lead generation
  resources :leads, only: [:create]

end

app/models/pickup.rb
class Pickup < ApplicationRecord
  belongs_to :order
  validates :uncomplete, inclusion: { in: [true, false] }
  validates :airport, inclusion: { in: ["Paris CDG", "Paris Orly", "London Heathrow", "London Gatwick"], if: :complete? }
  validates :arrival, presence: { if: :complete? }
  validates :flight_number, presence: { if: :complete? }
  validate :arrival_cannot_be_in_the_past, { if: :complete? }

  AIRPORTS_FR = ["Paris CDG", "Paris Orly"]
  AIRPORTS_GB = ["London Heathrow", "London Gatwick"]

  def arrival_cannot_be_in_the_past
    errors.add(:arrival, "can't be in the past") if arrival.present? && arrival < Time.zone.now
  end

  def complete?
    !uncomplete
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :redirect_if_order_is_paid, only: [:new]

  def new
    @order = Order.find(params[:order_id])
    @pickup = @order.pickup || Pickup.new
    @message = { content: "Alright, almost done! I just need your flight details to arrange your airport pickup. ", delay: 0 }
  end
end

app/views/steps/pickup/_form.html.erb
<%= simple_form_for pickup, url: new_pickup_path(order), data: {reflex: "submit->PickupReflex#create", reflex_serialize_form: true } do |f| %>
  <div class="d-flex">
    <%= f.check_box :uncomplete, required: true, checked: false, data: {action: 'change->animate#toggleInputs'}, input_html: {class: "custom-checkbox"} %>
    <label class='w-100 ms-2'>I don’t have my flight details yet. Please contact me again at a later point in time to arrange the airport pick-up</label>
  </div>
  <hr>
  <div class="inputs">
    <div class="d-flex lines-input">
    <%= f.input :arrival, as: :string, label: 'Date of arrival',
               required: true,
               input_html: { class:'datepicker', data: {
                controller: "flatpickr", flatpickr_date_format: "d-m-Y", flatpickr_min_date: Time.zone.now} } %>
    <%= f.input :flight_number, required: true, placeholder: "LH20038" %>
    </div>
    <%= f.input :airport, collection: (order.fr? ? Pickup::AIRPORTS_FR : Pickup::AIRPORTS_GB), prompt: 'Select your aiport', input_html: {class: 'custom-select'} %>
    <label class="mb-4">Please note that our drivers will only be able to drop you off in central London locations.<br><br>
    Your driver will be waiting for you at arrivals. Should you need assistance, please contact us.</label>
  </div>
  <hr>
  <%= f.button :submit, 'Continue' , class: 'btn-main mb-2' %>
  <%= link_to 'Back', new_shipping_path(order.id), class:'btn-main-white mb-5' %>
<% end %>

app/views/steps/pickup/_new.html.erb
<div class="flow-container" data-controller="animate">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xs-12 col-lg-6">
      <%= render 'shared/chat', message: message %>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-xs-12 col-lg-6">
        <div class="content-container" data-delay="2" data-animate-target="contentContainer">
          <div class="form-base">
            <%= render 'steps/pickup/form', pickup: pickup, order: order %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/steps/pickup/_pickup.html.erb
<div class="flow-container" data-controller="animate">
  <div class="container">
      <%= render 'shared/chat', message: message %>
      <div class="content-container" data-delay="2" data-animate-target="contentContainer">
        <div class="form-base">
          <%= render 'steps/pickup/pickup_form', pickup: pickup, order: order %>
        </div>
    </div>
  </div>
</div>

app/views/steps/pickup/_pickup_form.html.erb
<%= simple_form_for pickup, url: new_pickup_path(order), data: {reflex: "submit->PickupReflex#create", reflex_serialize_form: true } do |f| %>
  <%= f.check_box :uncomplete, required: true, checked: false, data: {action: 'change->animate#toggleInputs'} %>
  <div class="inputs">
    <%= f.input :arrival, as: :string,
               required: true,
               input_html: { class:'datepicker', data: {
                controller: "flatpickr", flatpickr_date_format: "d-m-Y", flatpickr_min_date: Time.zone.now} } %>
    <%= f.input :flight_number, required: true %>`
    <%= f.input :airport, collection: (order.fr? ? Pickup::AIRPORTS_FR : Pickup::AIRPORTS_GB), prompt: 'Select your aiport', input_html: {class: 'custom-select'} %>
  </div>
  <%= f.button :submit, 'Continue' , class: 'btn-main' %>
<% end %>